import Head from "next/head";
import { Header, Footer } from "../../components/index.js";
import { About } from "./components/About.jsx";
import { Info } from "./components/Info.jsx";
import { WhyLatch } from "./components/WhyLatch.jsx";
export default function Home() {
  return (
    <div className="page">
      <h1 style={style.h1}>LatchBio</h1>
      <Head>
        <title>LatchBio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container">
        <Info />
        <About />
        <WhyLatch />
      </main>
      <Footer />
    </div>
  );
}
const style = {
  h1: {
    display: "none",
  },
};
